[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
hourglass_protocol = "83PYe3dvbceG6KH98pewdyxLfhLFTHQUc8sjJXiKAcij"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
