[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
hourglass_protocol = "83PYe3dvbceG6KH98pewdyxLfhLFTHQUc8sjJXiKAcij"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=b512dcfe-ee18-42ea-b3c7-82dab825d317"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
